# Generated by Django 4.0.1 on 2022-01-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_table1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Principle',
            },
        ),
    ]
