# Generated by Django 4.0.1 on 2022-01-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.college'),
        ),
    ]
