# Generated by Django 4.0.1 on 2022-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_principal_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intake', models.IntegerField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
