# Generated by Django 4.0.1 on 2022-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0008_rename_subject_student_subject_nm_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
